package final02;

/**
 * @author Robin Fritz
 * @version 1.0
 */
public class StudentPortal {
    private Professor professor;
    private Instructor instructor;
    private Student student;
    private Module module;
    private Lecture lecture;
    private Exercise exercise;

    public StudentPortal() {
        professor = new Professor();
        instructor = new Instructor();
        student = new Student();
        module = new Module();
        lecture = new Lecture();
        exercise = new Exercise();
    }

    /**
     * Switch for add commands.
     *
     * @param param String array with parameters
     * @return Returns a String generated by the executed method
     * @throws InputException For input format type errors
     */
    public String add(String[] param) throws InputException {
        switch (param[0]) {
            case "add-professor":
                return addProfessor(param);

            case "add-instructor":
                return addInstructor(param);

            case "add-student":
                return addStudent(param);

            case "add-module":
                return addModule(param);

            case "add-lecture":
                return addLecture(param);

            case "add-exercise":
                return addExercise(param);

            default:
                throw new InputException("wrong input format!");
        }
    }

    public String list(String[] param) throws InputException {
        switch (param[0]) {
            case "list-professor":
                return listProfessor();

            case "list-instructor":
                return listInstructor();

            case "list-student":
                return listStudent();

            case "list-module":
                return listModule();

            case "list-lecture":
                return listLecture();

            case "list-exercise":
                return listExercise();

            default:
                throw new InputException("wrong input!");
        }
    }

    public String summary(String[] param) throws InputException {
        switch (param[0]) {
            case "summary-professor":
                return summProfessor(param);

            case "summary-instructor":
                return summInstructor(param);

            case "summary-student":
                return summStudent(param);

            case "summary-module":
                return summModule(param);

            case "summary-lecture":
                return summLecture(param);

            case "summary-exercise":
                return summExercise(param);

            default:
                throw new InputException("wrong input!");
        }
    }

    public String examination(String[] param) throws InputException {
        switch (param[0]) {
            case "examination-competence":
                return examCompetence(param);

            case "examination-marking":
                return examMarking(param);

            default:
                throw new InputException("wrong input!");
        }
    }

    private String addProfessor(String[] param) throws InputException {
        return professor.addProf(param);
    }

    private String listProfessor() {
        return professor.listProf();
    }

    private String summProfessor(String[] param) {
        return professor.summProf(param);
    }

    private String addInstructor(String[] param) throws InputException {
        return instructor.addInstr(param);
    }

    private String listInstructor() {
        return instructor.listInstr();
    }

    private String summInstructor(String[] param) {
        return instructor.summInstr(param);
    }

    private String addStudent(String[] param) throws InputException {
        return student.addStud(param);
    }

    private String listStudent() {
        return student.listStud();
    }

    private String summStudent(String[] param) {
        return student.summStud(param);
    }

    private String addModule(String[] param) throws InputException {
        return module.addModule(param);
    }

    private String listModule() {
        return module.listModule();
    }

    private String summModule(String[] param) {
        return module.summModule(param);
    }

    private String addLecture(String[] param) throws InputException {
        return lecture.addLecture(param);
    }

    private String listLecture() {
        return lecture.listLecture();
    }

    private String summLecture(String[] param) {
        return lecture.summLecture(param);
    }

    private String addExercise(String[] param) throws InputException {
        return exercise.addExercise(param);
    }

    private String listExercise() {
        return exercise.listExercise();
    }

    private String summExercise(String[] param) {
        return exercise.summExercise(param);
    }

    private String examCompetence(String[] param) {
        return exam.examCompetence(param);
    }

    private String examMarking(String[] param) {
        return exam.examMarking(param);
    }
}
