package final02;

/**
 * @author Robin Fritz
 * @version 1.0
 */
public class StudentPortal {

    /**
     * Switch for add commands.
     *
     * @param param String array with parameters
     * @return Returns a String generated by the executed method
     * @throws InputException For input format type errors
     */
    public String add(String[] param) throws InputException {
        switch (param[0]) {
            case "add-professor":
                return addProfessor();

            case "add-instructor":
                return addInstructor();

            case "add-student":
                return addStudent();

            case "add-module":
                return addModule();

            case "add-lecture":
                return addLecture();

            case "add-exercise":
                return addExercise();

            default:
                throw new InputException("wrong input format!");
        }
    }

    public String list(String[] param) throws InputException {
        switch (param[0]) {
            case "list-professor":
                return listProfessor();

            case "list-instructor":
                return listInstructor();

            case "list-student":
                return listStudent();

            case "list-module":
                return listModule();

            case "list-lecture":
                return listLecture();

            case "list-exercise":
                return listExercise();

            default:
                throw new InputException("wrong input!");
        }
    }

    public String summary(String[] param) throws InputException {
        switch (param[0]) {
            case "summary-professor":
                return summProfessor();

            case "summary-instructor":
                return summInstructor();

            case "summary-student":
                return summStudent();

            case "summary-module":
                return summModule();

            case "summary-lecture":
                return summLecture();

            case "summary-exercise":
                return summExercise();

            default:
                throw new InputException("wrong input!");
        }
    }

    public String examination(String[] param) throws InputException {
        switch (param[0]) {
            case "examination-competence":
                return examCompetence();

            case "examination-marking":
                return examMartking();

            default:
                throw new InputException("wrong input!");
        }
    }

    private String addProfessor() {

    }

    private String listProfessor() {

    }

    private String summProfessor() {

    }

    private String addInstructor() {

    }

    private String listInstructor() {

    }

    private String summInstructor() {

    }

    private String addStudent() {

    }

    private String listStudent() {

    }

    private String summStudent() {

    }

    private String addModule() {

    }

    private String listModule() {

    }

    private String summModule() {

    }

    private String addLecture() {

    }

    private String listLecture() {

    }

    private String summLecture() {

    }

    private String addExercise() {

    }

    private String listExercise() {

    }

    private String summExercise() {

    }

    private String examCompetence() {

    }

    private String examMartking() {

    }
}
